# Generated by Django 5.2.4 on 2025-08-17 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_customernames'),
    ]

    operations = [
        migrations.CreateModel(
            name='GamesTypes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gameName', models.CharField(max_length=100, unique=True)),
            ],
        ),
    ]
