# Generated by Django 5.2.4 on 2025-08-17 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_gamestypes'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameRecords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('gameName', models.CharField(max_length=255)),
                ('content', models.TextField()),
            ],
        ),
    ]
