# Generated by Django 5.2.4 on 2025-08-17 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_gamerecords'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameDashBoard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('totalAmount', models.FloatField()),
                ('date', models.DateField()),
            ],
        ),
    ]
