# Generated by Django 5.2.4 on 2025-08-19 12:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_gamedashboard'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamerecords',
            name='date',
            field=models.DateField(default=datetime.date(2025, 8, 18)),
            preserve_default=False,
        ),
    ]
