# Generated by Django 5.2.4 on 2025-08-19 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_gamerecords_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameWinningNumbersRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('records', models.TextField()),
            ],
        ),
    ]
