# Generated by Django 5.2.4 on 2025-09-05 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0008_phonepeamount'),
    ]

    operations = [
        migrations.CreateModel(
            name='BakiJamaAmounts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=50)),
                ('amount', models.FloatField()),
                ('date', models.DateField()),
            ],
        ),
        migrations.DeleteModel(
            name='PhonePeAmount',
        ),
    ]
